SELECT SUBSTR(WAITS.METRIC_NAME, 1, 25) AS METRIC_NAME,
       WAITS.TOTAL_TIME_VALUE,
       WAITS.COUNT
FROM TABLE(MON_GET_PKG_CACHE_STMT_DETAILS(NULL,NULL,NULL, -1)) AS STMT_METRICS
    ,XMLTABLE ( XMLNAMESPACES( DEFAULT 'http://www.ibm.com/xmlns/prod/db2/mon'), '$DETMETRICS/db2_pkg_cache_stmt_details'
       PASSING   XMLPARSE(DOCUMENT STMT_METRICS.DETAILS) as "DETMETRICS"
       COLUMNS "STMT_TEXT"               CLOB       PATH 'stmt_text',
               "INSERT_TIMESTAMP"        TIMESTAMP  PATH 'insert_timestamp'
     ) AS DETMETRICS
    ,TABLE( MON_FORMAT_XML_WAIT_TIMES_BY_ROW(STMT_METRICS.DETAILS) ) AS WAITS
WHERE DETMETRICS.STMT_TEXT like '%<my_cool_query_match_pattern>%'
  AND DETMETRICS.INSERT_TIMESTAMP > CURRENT TIMESTAMP - 10 MINUTES
ORDER BY WAITS.TOTAL_TIME_VALUE DESC;
